#!/bin/sh
# build the go project, check if succesfull
# if success, mv executable to an .o file for .gitinore
# then run
clear
go build
if [ $? -eq 0 ]; then
	fld=${PWD##*/}
	if [ -f $fld ]; then
		mv $fld ${fld}.o
		if [ "$1" = "test" ]; then
			echo 'sucess'
		else
			echo 'running'
			./${fld}.o
		fi
	fi
else
	echo 'error'
fi
