#!/bin/sh
# build the go project, check if succesfull
# if success, mv executable to an .o file for .gitinore
# then run
clear
go build
if [ $? -eq 0 ]; then
	fld=${PWD##*/}
	if [ -f $fld ]; then
		mv $fld ${fld}.o
		echo 'running'
		./${fld}.o
	else
		echo 'built'
	fi
else
	echo 'error'
fi
